### ISSUE TITLE
Add CLI

### ISSUE THREAD

**Issue by austin3dickey** [conbench/benchalerts#4]
Add a thin CLI around some package functionality that needs to be exposed in [RMarkdown/quarto](https://github.com/conbench/benchalerts/pull/2#pullrequestreview-1087512202) reports.

TODO: determine exactly which functionality to expose.

**Comment by alistaire47** [comment]
Slack posting would be nice, e.g. something like `benchalert slack --channel=benchmark-alerts "very fast much good"` or whatnot (assuming host is set by an env var). I defer to @boshek if he's got ideas of how this might work, though.

The need for posting to PRs seems lower, as most of that is arranged in python anyway I think? Still good though.

**Comment by austin3dickey** [comment]
That makes sense. Overall, I'm thinking the scope of this package is:
1. assume runs are already in conbench
2. given some sort of identifier of contender run(s), pull the comparisons between those run(s) and their baseline(s)
3. do Data Science™ on the comparisons to identify anomalies
4. conditionally post alerts to different places

(3) and (4) would be configurable by the script calling `benchalerts`, but I think we'd like to always do these steps in this package so we don't duplicate efforts in other places. Maybe we could scope the CLI with that in mind?

**Comment by boshek** [comment]
I think in the long run a CLI is probably useful. That said, I've pretty impressed lately with how well python works in quarto/rmarkdown even with mixed languages in one document. To me a python chunk that calls the benchalerts package is a bit cleaner that shelling out though I expect in some cases it will end up making more sense to shell out. So options are good.

**Comment by alistaire47** [comment]
> I've pretty impressed lately with how well python works in quarto/rmarkdown even with mixed languages in one document.

My experience has been that selecting the right python env and passing data back and forth is finicky, but a. it's been a while since I've tried, and b. this is a pretty simple use-case, so maybe it's fine. But in my head this would be a global utility installed with pipx like datalogistik.

> Overall, I'm thinking the scope of this package is:
> 
> 1. assume runs are already in conbench
> 2. given some sort of identifier of contender run(s), pull the comparisons between those run(s) and their baseline(s)
> 3. do Data Science™ on the comparisons to identify anomalies
> 4. conditionally post alerts to different places

Wait, the DS would live in this package? I assumed this was just a util package; it's a lot less useful as such if it ends up with a bunch of heavy DS deps.

The other missing part of that is reporting (which we probably want to keep in RMarkdown/quarto); in some workflows we'll want to generate full reports. Maybe we need to go back and figure out how components map to needs defined by use-cases; I'm fuzzy on how this is supposed to all fit together and run.

**Comment by jonkeane** [comment]
> do Data Science™ on the comparisons to identify anomalies

> Wait, the DS would live in this package? I assumed this was just a util package; it's a lot less useful as such if it ends up with a bunch of heavy DS deps.

Yeah, IMO, these types of things should probably actually live in conbench server | the conbench API, such that the alerter package is minimal + clean. The alerter package might have some defaults that it could set or alter (e.g. how big of a zscore counts as a regression?). We don't currently have the conbench server|API facility to do that, so we might need to write some code in alerter that does something like that and then move that up when we make the changes to the conbench API that allows that to happen.

As for if we want to wrap this as a CLI or not: I would vote do the least possible work until we actually experience pain by this. So defer any possible CLI making until we actually run this somewhere where that would be helpful.

**Comment by austin3dickey** [comment]
>these types of things should probably actually live in conbench server | the conbench API

This does sound like an ideal solution in the long-term.

> defer any possible CLI making

Yeah, if we could try to run python chunks in R Markdown, that would definitely be nicer for input/configuration and output parsing. And cut down on code to maintain in this package.

**Comment by austin3dickey** [comment]
Going to close this until we determine it's necessary.
